-- Données de démonstration
--
-- Les données sensibles (n° de sécurité sociale, notes, prestations) sont chiffrées
-- par l'application avec ENCRYPTION_KEY : elles ne peuvent pas être insérées en SQL brut.
-- Le compte de démonstration est donc créé par un script TypeScript (scripts/seed.ts) :
--
--   npm run db:seed                  Supabase local
--   npm run db:seed -- --remote      projet hébergé
