-- Seed data for testing
-- This file is used by Supabase to seed the database with test data

-- Note: You'll need to create a test user first through the auth system
-- Then replace the UUID below with your actual test user ID

-- Example: Create a test user profile (uncomment and replace with your user ID)
-- INSERT INTO public.profiles (id, email, is_pro, full_name, specialty, address, phone, siret, adeli)
-- VALUES (
--     'YOUR_USER_ID_HERE'::uuid,
--     'test@example.com',
--     false,
--     'Dr. Jean Martin',
--     'Infirmier libéral',
--     '123 Rue de la Santé, 75014 Paris',
--     '01 23 45 67 89',
--     '123 456 789 00012',
--     '750123456'
-- );

-- Example: Create test folders
-- INSERT INTO public.folders (user_id, name, color)
-- VALUES
--     ('YOUR_USER_ID_HERE'::uuid, 'Clients Réguliers', 'blue'),
--     ('YOUR_USER_ID_HERE'::uuid, 'Urgences', 'red'),
--     ('YOUR_USER_ID_HERE'::uuid, 'Pédiatrie', 'green');

-- Example: Create test invoices
-- INSERT INTO public.invoices (user_id, number, date, due_date, status, template, client, items, notes, folder_id)
-- VALUES
--     (
--         'YOUR_USER_ID_HERE'::uuid,
--         'FAC-2025-001',
--         '2025-01-15',
--         '2025-02-15',
--         'Envoyée',
--         'modern',
--         '{"name": "Marie Dubois", "address": "45 Avenue des Fleurs, 75015 Paris", "email": "marie.dubois@email.com", "ssn": "2 85 12 75 123 456 78"}'::jsonb,
--         '[
--             {"id": "1", "description": "Consultation à domicile", "quantity": 1, "unitPrice": 35},
--             {"id": "2", "description": "Pansement complexe", "quantity": 1, "unitPrice": 15}
--         ]'::jsonb,
--         'Patient très satisfait. Rendez-vous de suivi prévu.',
--         (SELECT id FROM public.folders WHERE name = 'Clients Réguliers' LIMIT 1)
--     ),
--     (
--         'YOUR_USER_ID_HERE'::uuid,
--         'FAC-2025-002',
--         '2025-01-16',
--         '2025-02-16',
--         'Brouillon',
--         'classic',
--         '{"name": "Pierre Leroy", "address": "12 Rue de la Paix, 75002 Paris", "email": "pierre.leroy@email.com"}'::jsonb,
--         '[
--             {"id": "1", "description": "Injection intramusculaire", "quantity": 1, "unitPrice": 20},
--             {"id": "2", "description": "Prélèvement sanguin", "quantity": 1, "unitPrice": 15}
--         ]'::jsonb,
--         'Première visite. Renouveler dans 3 jours.',
--         NULL
--     ),
--     (
--         'YOUR_USER_ID_HERE'::uuid,
--         'FAC-2025-003',
--         '2024-12-20',
--         '2025-01-20',
--         'Payée',
--         'elegant',
--         '{"name": "Sophie Martin", "address": "89 Boulevard Saint-Germain, 75005 Paris", "email": "sophie.martin@email.com", "ssn": "1 75 04 75 987 654 32"}'::jsonb,
--         '[
--             {"id": "1", "description": "Soins post-opératoires", "quantity": 3, "unitPrice": 40},
--             {"id": "2", "description": "Changement de pansement", "quantity": 3, "unitPrice": 10}
--         ]'::jsonb,
--         'Cicatrisation excellente. Traitement terminé.',
--         (SELECT id FROM public.folders WHERE name = 'Clients Réguliers' LIMIT 1)
--     );

-- To use this seed file:
-- 1. Create a test user through your app's signup
-- 2. Get the user ID from Supabase Dashboard (Authentication > Users)
-- 3. Replace 'YOUR_USER_ID_HERE' with the actual UUID
-- 4. Uncomment the INSERT statements
-- 5. Run: supabase db reset (this will run migrations and seed data)
