import { createClient } from '@/lib/supabase/server'
import { NextResponse } from 'next/server'
import { encrypt, decrypt } from '@/lib/encryption'
import { logAuditAction } from '@/lib/audit'

export async function GET() {
    const supabase = await createClient()

    try {
        const { data: { user }, error: authError } = await supabase.auth.getUser()

        if (authError || !user) {
            return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
        }

        const { data, error } = await supabase
            .from('invoices')
            .select('*')
            .eq('user_id', user.id)
            .is('deleted_at', null)
            .order('created_at', { ascending: false })

        if (error) {
            // Handle missing table error gracefully
            if (error.code === '42P01') {
                return NextResponse.json([])
            }
            throw error
        }

        // Decrypt sensitive data (SSN)
        const decryptedData = data.map((invoice: any) => {
            if (invoice.client && invoice.client.ssn) {
                return {
                    ...invoice,
                    client: {
                        ...invoice.client,
                        ssn: decrypt(invoice.client.ssn)
                    }
                }
            }
            return invoice
        })

        // Log Audit Action (Async, don't await to not block response)
        logAuditAction({
            action: 'VIEW_INVOICES',
            resourceType: 'invoice',
            userId: user.id,
            details: { count: data.length }
        });

        return NextResponse.json(decryptedData)
    } catch (error: any) {
        console.error('Error fetching invoices:', error)
        return NextResponse.json(
            { error: error.message || 'Internal Server Error' },
            { status: 500 }
        )
    }
}

export async function POST(request: Request) {
    const supabase = await createClient()

    try {
        const { data: { user }, error: authError } = await supabase.auth.getUser()

        if (authError || !user) {
            return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
        }

        const body = await request.json()
        const { invoice } = body

        if (!invoice) {
            return NextResponse.json({ error: 'Invoice data is required' }, { status: 400 })
        }

        // Validation
        const errors: string[] = []
        // if (!invoice.number) errors.push('Invoice number is required') // Auto-generated by DB
        if (!invoice.date) errors.push('Invoice date is required')
        if (!invoice.client || !invoice.client.name) errors.push('Client name is required')
        if (!invoice.items || invoice.items.length === 0) errors.push('At least one item is required')

        if (errors.length > 0) {
            return NextResponse.json({ error: 'Validation failed', errors }, { status: 400 })
        }

        // Encrypt sensitive data (SSN)
        const invoiceToSave = { ...invoice }
        if (invoiceToSave.client && invoiceToSave.client.ssn) {
            invoiceToSave.client = {
                ...invoiceToSave.client,
                ssn: encrypt(invoiceToSave.client.ssn)
            }
        }

        const payload = {
            ...invoiceToSave,
            user_id: user.id,
            updated_at: new Date().toISOString(),
            ...(!invoice.id && { created_at: new Date().toISOString() })
        }

        const { data, error } = await supabase
            .from('invoices')
            .upsert(payload, { onConflict: 'id' })
            .select()
            .single()

        if (error) {
            if (error.code === '23505') {
                return NextResponse.json({ error: 'Invoice number already exists' }, { status: 409 })
            }
            throw error
        }

        // Log Audit Action
        const actionType = invoice.id ? 'UPDATE_INVOICE' : 'CREATE_INVOICE';
        logAuditAction({
            action: actionType,
            resourceType: 'invoice',
            resourceId: data.id,
            userId: user.id,
            details: { invoiceNumber: data.number }
        });

        const responseData = { ...data }
        if (responseData.client && responseData.client.ssn) {
            responseData.client = {
                ...responseData.client,
                ssn: decrypt(responseData.client.ssn)
            }
        }

        return NextResponse.json({ data: responseData, success: true })

    } catch (error: any) {
        console.error('Error saving invoice:', error)
        return NextResponse.json(
            { error: error.message || 'Internal Server Error' },
            { status: 500 }
        )
    }
}
