import { z } from 'zod';
import { InvoiceStatus } from '@/types';

export const LineItemSchema = z.object({
    id: z.uuid().optional(),
    description: z.string({ message: "La description de la prestation est requise" }).min(1, "La description est requise"),
    quantity: z.number({ message: "La quantité est requise" }).min(0.0001, "La quantité doit être positive"), // Relaxed min slightly
    unitPrice: z.number({ message: "Le prix unitaire est requis" }).min(0, "Le prix unitaire ne peut pas être négatif"),
});

export const ClientSchema = z.object({
    name: z.string({ message: "Le nom du client est requis" }).min(1, "Le nom du client est requis"),
    address: z.string().nullable().optional().or(z.literal('')),
    email: z.email("Email invalide").nullable().optional().or(z.literal('')),
    ssn: z.string().nullable().optional().or(z.literal('')), // Will be encrypted on server
});

export const InvoiceSchema = z.object({
    id: z.uuid().optional(),
    number: z.string().optional(), // Generated by DB or passed for updates
    date: z.string({ message: "La date de la facture est requise" }).regex(/^\d{4}-\d{2}-\d{2}$/, "Format de date invalide (YYYY-MM-DD)"),
    dueDate: z.string({ message: "La date d'échéance est requise" }).regex(/^\d{4}-\d{2}-\d{2}$/, "Format de date invalide (YYYY-MM-DD)"),
    status: z.enum(InvoiceStatus).optional().default(InvoiceStatus.DRAFT),
    template: z.enum(['modern', 'classic', 'minimalist', 'elegant', 'corporate']).optional().default('modern'),
    client: ClientSchema,
    items: z.array(LineItemSchema).min(1, "Au moins une prestation est requise"),
    notes: z.string().nullable().optional().or(z.literal('')),
    folderId: z.uuid().nullable().optional().or(z.literal('')), // Handle empty string from select
    patientId: z.uuid().nullable().optional().or(z.literal('')),
    seller_snapshot: z.any().optional(),
});

export const UserProfileSchema = z.object({
    full_name: z.string().min(1, "Le nom complet est requis"),
    specialty: z.string().nullable().optional().or(z.literal('')),
    address: z.string().nullable().optional().or(z.literal('')),
    phone: z.string().nullable().optional().or(z.literal('')),
    siret: z.string().nullable().optional().or(z.literal('')),
    adeli: z.string().nullable().optional().or(z.literal('')),
    is_vat_applicable: z.boolean().optional(),
});

export const OnboardingSchema = UserProfileSchema.extend({
    siret: z.string()
        .regex(/^\d{14}$/, "Le SIRET doit contenir exactement 14 chiffres")
        .nullable()
        .optional()
        .or(z.literal('')),
    adeli: z.string()
        .regex(/^\d{9}$/, "Le numéro ADELI doit contenir exactement 9 chiffres")
        .nullable()
        .optional()
        .or(z.literal('')),
    phone: z.string()
        .regex(/^(?:(?:\+|00)33|0)\s*[1-9](?:[\s.-]*\d{2}){4}$/, "Format de téléphone invalide (ex: 06 12 34 56 78)")
        .nullable()
        .optional()
        .or(z.literal('')),
});

export const FolderSchema = z.object({
    id: z.uuid().optional(),
    name: z.string().min(1, "Le nom du dossier est requis"),
    color: z.string().optional().default('blue'),
});

export const PatientSchema = z.object({
    id: z.uuid().optional(),
    name: z.string().min(1, "Le nom est requis"),
    email: z.email("Email invalide").nullable().optional().or(z.literal('')),
    address: z.string().nullable().optional().or(z.literal('')),
    phone: z.string()
        .regex(/^(?:(?:\+|00)33|0)\s*[1-9](?:[\s.-]*\d{2}){4}$/, "Format de téléphone invalide")
        .nullable()
        .optional()
        .or(z.literal('')),
    ssn: z.string()
        .regex(/^[12]\d{2}(0[1-9]|1[0-2])(2[AB]|\d{2})\d{3}\d{3}(\d{2})?$/, "Numéro de sécurité sociale invalide (13 ou 15 chiffres)")
        .nullable()
        .optional()
        .or(z.literal('')),
    notes: z.string().nullable().optional().or(z.literal('')),
});

export const SignUpSchema = z.object({
    email: z.email("Email invalide"),
    password: z.string()
        .min(8, "8 caractères")
        .regex(/[A-Z]/, "une majuscule")
        .regex(/[a-z]/, "une minuscule")
        .regex(/[!@#$%^&*(),.?":{}|<>]/, "un caractère spécial"),
});

export type InvoiceInput = z.infer<typeof InvoiceSchema>;
export type UserProfileInput = z.infer<typeof UserProfileSchema>;
export type OnboardingInput = z.infer<typeof OnboardingSchema>;
export type FolderInput = z.infer<typeof FolderSchema>;
export type PatientInput = z.infer<typeof PatientSchema>;
