import { z } from 'zod';
import { InvoiceStatus } from '@/types';

export const LineItemSchema = z.object({
    id: z.string().uuid().optional(),
    description: z.string().min(1, "La description est requise"),
    quantity: z.number().min(0.01, "La quantité doit être positive"),
    unitPrice: z.number().min(0, "Le prix unitaire ne peut pas être négatif"),
});

export const ClientSchema = z.object({
    name: z.string().min(1, "Le nom du client est requis"),
    address: z.string().optional(),
    email: z.string().email("Email invalide").optional().or(z.literal('')),
    ssn: z.string().optional(), // Will be encrypted on server
});

export const InvoiceSchema = z.object({
    id: z.string().uuid().optional(),
    number: z.string().optional(), // Generated by DB or passed for updates
    date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, "Format de date invalide (YYYY-MM-DD)"),
    dueDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, "Format de date invalide (YYYY-MM-DD)"),
    status: z.nativeEnum(InvoiceStatus).optional().default(InvoiceStatus.DRAFT),
    template: z.enum(['modern', 'classic', 'minimalist', 'elegant', 'corporate']).optional().default('modern'),
    client: ClientSchema,
    items: z.array(LineItemSchema).min(1, "Au moins une prestation est requise"),
    notes: z.string().optional(),
    folderId: z.string().uuid().nullable().optional(),
    patientId: z.string().uuid().nullable().optional(),
});

export const UserProfileSchema = z.object({
    full_name: z.string().min(1, "Le nom complet est requis"),
    specialty: z.string().optional(),
    address: z.string().optional(),
    phone: z.string().optional(),
    siret: z.string().optional(),
    adeli: z.string().optional(),
});

export const OnboardingSchema = UserProfileSchema.extend({
    siret: z.string()
        .regex(/^\d{14}$/, "Le SIRET doit contenir exactement 14 chiffres")
        .optional()
        .or(z.literal('')),
    adeli: z.string()
        .regex(/^\d{9}$/, "Le numéro ADELI doit contenir exactement 9 chiffres")
        .optional()
        .or(z.literal('')),
    phone: z.string()
        .regex(/^(?:(?:\+|00)33|0)\s*[1-9](?:[\s.-]*\d{2}){4}$/, "Format de téléphone invalide (ex: 06 12 34 56 78)")
        .optional()
        .or(z.literal('')),
});

export const FolderSchema = z.object({
    id: z.string().uuid().optional(),
    name: z.string().min(1, "Le nom du dossier est requis"),
    color: z.string().optional().default('blue'),
});

export const PatientSchema = z.object({
    id: z.string().uuid().optional(),
    name: z.string().min(1, "Le nom est requis"),
    email: z.string().email("Email invalide").optional().or(z.literal('')),
    address: z.string().optional(),
    phone: z.string()
        .regex(/^(?:(?:\+|00)33|0)\s*[1-9](?:[\s.-]*\d{2}){4}$/, "Format de téléphone invalide")
        .optional()
        .or(z.literal('')),
    ssn: z.string()
        .regex(/^[12]\d{2}(0[1-9]|1[0-2])(2[AB]|\d{2})\d{3}\d{3}(\d{2})?$/, "Numéro de sécurité sociale invalide (13 ou 15 chiffres)")
        .optional()
        .or(z.literal('')),
    notes: z.string().optional(),
});

export const SignUpSchema = z.object({
    email: z.string().email("Email invalide"),
    password: z.string()
        .min(8, "8 caractères")
        .regex(/[A-Z]/, "une majuscule")
        .regex(/[a-z]/, "une minuscule")
        .regex(/[!@#$%^&*(),.?":{}|<>]/, "un caractère spécial"),
});

export type InvoiceInput = z.infer<typeof InvoiceSchema>;
export type UserProfileInput = z.infer<typeof UserProfileSchema>;
export type OnboardingInput = z.infer<typeof OnboardingSchema>;
export type FolderInput = z.infer<typeof FolderSchema>;
export type PatientInput = z.infer<typeof PatientSchema>;
